# Info about you
name: Daniel Mendoza
position: Petroleum Engineer
email: Dmendozac90@gmail.com
#company_name: C.H. Robinson
#company_url: https://www.chrobinson.com/
place_name: Greeley, CO

# Blog info
title: Daniel Mendoza
description: Blog
url: http://dmendozac90.github.io/

# Social links
github_url: https://github.com/dmendozac90
linkedin_url: http://www.linkedin.com/in/daniel-mendoza-398618148
social:
  links:
    - http://www.linkedin.com/in/daniel-mendoza-398618148
    - https://github.com/dmendozac90

# Images + files
logo: /assets/portfolio.png
#cv_url: /assets/files/
resume_url: /assets/files/Daniel_Mendoza_Resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-fontello
highlighter: rouge
color_mode: dark  # auto, light, or dark
comments: true
disqus_shortname: dmendozac90-github-io
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: 404b57
  tag_hover: 1f242a
  header_background: 1f242a
  header_text: ebebeb
  header_link_hover: 3aa6fb
  links: 3aa6fb
  links_visited: 0a0a0a

# Colors - dark mode
colors_dark:
  background: 292929
  text: ffffff
  tag: 353638
  tag_hover: 1a1a1b
  header_background: 1a1a1a
  header_text: ffffff
  header_link: ffffff
  header_link_hover: fa7970
  links: fb9089
  links_visited: fb9089